var name = prompt("Enter your name:");
document.write("Hello, " + name);
document.write("<br>");
var age = parseInt(prompt("Enter your age:"));
document.write("You are " + age + " years old.");
document.write("<br>");
document.write("next year you will be " + (age + 1) + " years old.");
var num1 = parseInt(prompt("Enter num1:"));
var num2 = parseInt(prompt("Enter num2:"));
var sum = num1 + num2;
var difference = num1 - num2;
var multi = num1 * num2;
var divi = num1 / num2;
document.write("<br>");
document.write("The sum of " + num1 + " and " + num2 + " is: " + sum);
document.write("<br>");
document.write("The difference of " + num1 + " and " + num2 + " is: " + difference);
document.write("<br>");
document.write("The multiplication of " + num1 + " and " + num2 + " is: " + multi);
document.write("<br>");
document.write("The division of " + num1 + " and " + num2 + " is: " + divi);
